# Generated by Django 4.1.13 on 2025-11-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("number", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("about", "About"),
                            ("resume", "Resume"),
                            ("both", "Both"),
                        ],
                        default="resume",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EducationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("about", "About"),
                            ("resume", "Resume"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("period", models.CharField(max_length=100)),
                ("grade", models.CharField(blank=True, max_length=100)),
                (
                    "highlights",
                    models.TextField(blank=True, help_text="One highlight per line"),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExperienceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("about", "About"),
                            ("resume", "Resume"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                ("period", models.CharField(max_length=100)),
                ("employment_type", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "achievements",
                    models.TextField(
                        blank=True,
                        help_text="One achievement/bullet per line (used on About page)",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Abdul Sattar", max_length=100)),
                (
                    "title",
                    models.CharField(
                        default="AI Engineer & ML Specialist", max_length=150
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        default="AI Engineer & ML Specialist specializing in NLP & GenAI",
                        max_length=255,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="Lahore, Punjab, Pakistan", max_length=150
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="malikabdulsattar9947@gmail.com", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("short_bio", models.TextField(blank=True)),
                (
                    "current_position",
                    models.CharField(
                        default="Currently Working at RoyalSoft",
                        help_text="Text for home page status badge, e.g. 'Currently Working at RoyalSoft'",
                        max_length=200,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Professional summary shown on About & Resume pages (supports paragraphs)",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile image for navbar/home/footer",
                        upload_to="profile/",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResumeProjectHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("text", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=150)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("about", "About"),
                            ("resume", "Resume"),
                            ("both", "Both"),
                        ],
                        default="about",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="technology",
            name="featured_on_home",
            field=models.BooleanField(
                default=False,
                help_text="Display this tech on the home page hero tech stack",
            ),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=150)),
                (
                    "level",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="0-100 proficiency (used for About skill bars)",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="portfolio.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
