# Generated by Django 4.1.13 on 2025-11-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_aboutstat_certification_educationentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="kaggle_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_url",
            field=models.URLField(
                blank=True,
                help_text="Full WhatsApp link, e.g. https://wa.me/... with message",
            ),
        ),
    ]
