# Generated by Django 4.1.13 on 2025-11-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_sitesettings_kaggle_url_sitesettings_whatsapp_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="profile",
            name="headline",
            field=models.CharField(
                help_text="One-line professional headline (shown on Home/About)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(max_length=100),
        ),
    ]
