# Generated by Django 4.1.13 on 2025-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_alter_profile_email_alter_profile_headline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="current_position",
            field=models.CharField(
                blank=True,
                help_text="Text for home page status badge (e.g., 'Currently Working at RoyalSoft')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Your contact email address", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Your location (e.g., Lahore, Pakistan)",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                help_text="Your full name (e.g., Abdul Sattar)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Your phone number", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="short_bio",
            field=models.TextField(blank=True, help_text="Brief bio about yourself"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.CharField(
                help_text="Your professional title (e.g., Full Stack Developer)",
                max_length=150,
            ),
        ),
    ]
