# Generated by Django 4.1.13 on 2026-01-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_profile_current_position_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='Your full name (e.g., Umer)', max_length=100),
        ),
    ]
